### ISSUE TITLE
setup canonical redirects for dirs

### ISSUE THREAD

**Issue by victoriabernard92** [cloudflare/worker-sites-template#24]
most sites don't want two responses for `blah/` and `blah` make sure missing the trailing slash 301s to the other

**Comment by ashleymichal** [comment]
many sites do not, but some do use `blah` while others use `blah/` because they put the assets at either `blah.html` or `blah/index.html`, depending on the generator. it may not be prudent to do this redirect in all cases, i think we can be more subtle in a future feature.

The debug logic in the PR is 💯  though.

**Comment by victoriabernard92** [comment]
I haven't heard of any customers actually requesting this and implementation is a little presumptive as @ashleymichal  mentioned, so going to wait to implement until after we get requests.
